### PR TITLE
Fix domain name

### LINKED ISSUE #48: Fix domain name
This is temporary solution until we can acquire the old domain again.

### PR DESCRIPTION
**Pull request by teoportase**
Closes #48

### CODE REVIEW

**Review by JonathanPartain — APPROVED** [review]
LGTM

**Comment by michalspano** [comment]
Good call. This, however, only updates the redirect link to `past-exams`, but we need to change the custom domain in (this) parent directory. To do that, we can (temporarily) remove `CNAME`. 

I reckon this can be a temporarily solution for now, until we receive funding for the domain (again).

**Comment by michalspano** [comment]
Great. We can also update the issue description implying that this is merely a **temporary** solution until we receive funding for the domain (again).

**Comment by teoportase** [comment]
> Great. We can also update the issue description implying that this is merely a **temporary** solution until we receive funding for the domain (again).

Issue description updated! Will merge PR now.

**Pull request merged**
