### PR TITLE
added a bunch of favicon stuff based on realfavicongenerator.net

### PR DESCRIPTION
**Pull request by JonathanPartain**
Aims to solve #9 plus more, for all platforms

### CODE REVIEW

**Review by michalspano — CHANGES_REQUESTED** [review]
I believe the `*.svg` icons can be removed! As you can see, they are not transpiled correctly (we've encountered this issue before); unless we obtain an `SVG` version of the logo, we'll need to disable this option.

**Comment by michalspano** [comment]
> I believe the `*.svg` icons can be removed! As you can see, they are not transpiled correctly (we've encountered this issue before); unless we obtain an `SVG` version of the logo, we'll need to disable this option.

Apart from that, it looks well!

**Comment by JonathanPartain** [comment]
All mentions of SVGs in the PR have been removed

**Review by michalspano — APPROVED** [review]
Approved!

**Pull request merged**
